name: pollution_source
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+2

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # 多语言支持
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  json_annotation: ^2.0.0
  cupertino_icons: ^0.1.2
  # 下拉刷新上拉加载库 https://github.com/xuelongqy/flutter_easyrefresh
  flutter_easyrefresh: ^2.0.8
  # 扩展嵌套滚动视图 https://github.com/fluttercandies/extended_nested_scroll_view
  extended_nested_scroll_view: ^0.3.6
  # Google 图表库 https://github.com/google/charts
  charts_flutter: ^0.8.1
  # 图表库 https://github.com/imaNNeoFighT/fl_chart
  fl_chart: ^0.8.1
  # 常用加载动画库 https://github.com/jogboms/flutter_spinkit
  flutter_spinkit: ^4.0.0
  # 动画库 https://github.com/2d-inc/Flare-Flutter
  flare_flutter: ^1.2.0
  # 网络请求库 https://github.com/flutterchina/dio
  dio: ^3.0.7
  # 矢量图控件 https://github.com/dnfield/flutter_svg
  flutter_svg: ^0.14.1
  # 启动URL的插件 https://github.com/flutter/plugins/tree/master/packages/url_launcher
  url_launcher: ^5.4.1
  # 城市选择控件 https://github.com/hanxu317317/city_pickers
  city_pickers: ^0.1.30
  # 业务逻辑与界面分离 https://github.com/felangel/bloc
  flutter_bloc: ^2.1.1
  # 简化实例比较 https://github.com/felangel/equatable
  equatable: ^0.6.0
  # 此包定义了可由dart sdk附带的工具使用的注释 https://github.com/dart-lang/sdk
  meta: ^1.1.6
  # 处理键盘事件 https://github.com/diegoveloper/flutter_keyboard_actions
  keyboard_actions: ^2.1.2
  # Flutter 常用工具类库 https://github.com/Sky24n/flustars
  flustars: 0.2.6+1
  # Toast插件 https://github.com/OpenFlutter/flutter_oktoast
  oktoast: ^2.2.0
  # 选择时间插件 https://github.com/dylanwuzh/flutter-cupertino-date-picker
  flutter_cupertino_date_picker: ^1.0.12
  # 下拉筛选菜单 https://github.com/GanZhiXiong/gzx_dropdown_menu
  gzx_dropdown_menu : ^1.0.1
  # 图片选择器 https://github.com/Sh1d0w/multi_image_picker
  multi_image_picker: ^4.6.1
  # 获取系统文件路径 https://github.com/flutter/plugins/tree/master/packages/path_provider
  path_provider: ^1.5.1
  # 打开文件 https://github.com/crazecoder/open_file
  open_file: ^2.1.1
  # 进度条dialog https://github.com/fayaz07/progress_dialog
  progress_dialog: ^1.2.0
  # 路由管理 https://github.com/theyakka/fluro
  fluro: ^1.5.1
  # 跨平台路径操作库 https://github.com/dart-lang/path
  path: ^1.6.4
  # 高德地图插件 https://github.com/best-flutter/flutter_amap_location
  amap_location: ^0.2.0
  # 权限申请 https://github.com/Baseflow/flutter-permission-handler
  permission_handler: '^4.2.0+hotfix.3'
  # 自动变更文本大小控件 https://github.com/leisim/auto_size_text
  auto_size_text: ^2.1.0
  # 获取应用版本信息 https://github.com/flutter/plugins/tree/master/packages/package_info
  package_info: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  #一次性生成 flutter packages pub run build_runner build
  #持续性生成 flutter packages pub run build_runner watch
  build_runner: ^1.0.0
  json_serializable: ^2.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/flare/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
