name: pollution_source
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # 多语言支持
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  # english_words: ^3.1.0
  # 下拉刷新上拉加载库 https://github.com/xuelongqy/flutter_easyrefresh
  flutter_easyrefresh: ^2.0.3
  # 扩展嵌套滚动视图 https://github.com/fluttercandies/extended_nested_scroll_view
  extended_nested_scroll_view: ^0.3.6
  json_annotation: ^2.0.0
  # percent_indicator: ^2.1.1
  # flutter_swiper : ^1.1.6
  # Google 图表库 https://github.com/google/charts
  charts_flutter: ^0.8.1
  # 图表库 https://github.com/aeyrium/bezier-chart
  # bezier_chart: ^1.0.15
  # 图表库(首页最近一周变化趋势和监测数据详情使用了) https://github.com/imaNNeoFighT/fl_chart
  # fl_chart: ^0.3.4
  fl_chart: ^0.5.0
  # 常用加载动画库 https://github.com/jogboms/flutter_spinkit
  flutter_spinkit: ^4.0.0
  # 动画库 https://github.com/2d-inc/Flare-Flutter
  flare_flutter: ^1.2.0
  # flutter_lottie: ^0.2.0
  # 网络请求库 https://github.com/flutterchina/dio
  # dio: ^2.1.16
  dio: ^3.0.7
  # 矢量图控件 https://github.com/dnfield/flutter_svg
  flutter_svg: ^0.14.1
  # 启动URL的插件 https://github.com/flutter/plugins/tree/master/packages/url_launcher
  # url_launcher: ^5.1.2
  url_launcher: ^5.1.4
  # 城市选择控件 https://github.com/hanxu317317/city_pickers
  city_pickers: ^0.1.25
  # 业务逻辑与界面分离 https://github.com/felangel/bloc
  # flutter_bloc: ^2.0.0
  flutter_bloc: ^2.1.1
  # 简化实例比较 https://github.com/felangel/equatable
  equatable: ^0.6.0
  # 此包定义了可由dart sdk附带的工具使用的注释 https://github.com/dart-lang/sdk
  meta: ^1.1.6
  # 处理键盘事件 https://github.com/diegoveloper/flutter_keyboard_actions
  keyboard_actions: ^2.1.2
  # 图片缓存 https://github.com/renefloor/flutter_cached_network_image
  cached_network_image: ^1.1.1
  # Dart 常用工具类库 https://github.com/Sky24n/common_utils
  common_utils: ^1.1.3
  # Flutter 常用工具类库 https://github.com/Sky24n/flustars
  flustars: 0.2.6+1
  # Toast插件 https://github.com/OpenFlutter/flutter_oktoast
  oktoast: ^2.2.0
  # 选择时间插件 https://github.com/Realank/flutter_datetime_picker
  # flutter_datetime_picker: ^1.2.8
  # 选择时间插件 https://github.com/dylanwuzh/flutter-cupertino-date-picker/blob/master/README_zh-cn.md
  flutter_cupertino_date_picker: ^1.0.12
  # 下拉筛选菜单 https://github.com/GanZhiXiong/gzx_dropdown_menu
  gzx_dropdown_menu : ^1.0.1
  # 图片选择器 https://github.com/Sh1d0w/multi_image_picker
  multi_image_picker: ^4.5.9
  # 获取系统文件路径 https://github.com/flutter/plugins/tree/master/packages/path_provider
  path_provider: ^1.4.5
  # 打开文件 https://github.com/crazecoder/open_file
  open_file: ^2.1.1
  # 进度条dialog https://github.com/fayaz07/progress_dialog
  progress_dialog: ^1.2.0
  # 路由管理 https://github.com/theyakka/fluro
  fluro: ^1.5.1
  # 扫码 https://github.com/apptreesoftware/flutter_barcode_reader
  # barcode_scan:
    # git:
      # url: https://github.com/simplezhli/flutter_barcode_reader.git

dev_dependencies:
  flutter_test:
    sdk: flutter

  #一次性生成 flutter packages pub run build_runner build
  #持续性生成 flutter packages pub run build_runner watch
  build_runner: ^1.0.0
  json_serializable: ^2.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    #    - assets/images/index_location.png
    #    - assets/images/index_header_bg.png
    #    - assets/images/indexbg.png
    #    - assets/images/button_bg_blue.png
    #    - assets/images/button_bg_green.png
    #    - assets/images/button_bg_pink.png
    #    - assets/images/icon_water_state.png
    #    - assets/images/icon_water_province.png
    #    - assets/images/icon_water_county.png
    #    - assets/images/icon_water_water.png
    #    - assets/images/icon_water_metal.png
    #    - assets/images/icon_monitor_all.png
    #    - assets/images/icon_monitor_online.png
    #    - assets/images/icon_monitor_alarm.png
    #    - assets/images/icon_monitor_over.png
    #    - assets/images/icon_monitor_offline.png
    #    - assets/images/icon_monitor_stop.png
    #    - assets/images/icon_card_title.png
    #    - assets/images/icon_aqi_examine_pm25.png
    #    - assets/images/icon_aqi_examine_quality.png
    #    - assets/images/icon_pollution_all_enter.png
    #    - assets/images/icon_pollution_point_enter.png
    #    - assets/images/icon_pollution_online_enter.png
    #    - assets/images/icon_pollution_water_enter.png
    #    - assets/images/icon_pollution_air_enter.png
    #    - assets/images/icon_pollution_air_water.png
    #    - assets/images/icon_pollution_water_outlet.png
    #    - assets/images/icon_pollution_air_outlet.png
    #    - assets/images/icon_pollution_licence_enter.png
    - assets/flare/
    - assets/images/
    # - assets/lottie/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
